### PR TITLE
use `strict: true` in project configuration, fix #36

### LINKED ISSUE #36: Incorrect return type for `toNullable` and `toUndefined`
I was looking at https://github.com/gcanti/fp-ts/issues/1337 and noticed that in place of a `Nullable<A>` as a return type, the docs currently show:

image

(Source: https://gcanti.github.io/fp-ts/modules/Option.ts.html#tonullable)

I'm not suggesting that we add `Nullable`, since this is a trivial type helper; however, I think there might be an issue with the documentation generator omitting `null` and `undefined`. This appears to affect the generated markdown for both `toUndefined` and `toNullable`, but there might be others.

Notice that the signatures in the module _do_ contain `null` and `undefined`.

image

(Source: https://github.com/gcanti/fp-ts/blob/master/src/Option.ts#L434)

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -40,12 +40,22 @@ const onRight: T.Task<void> = pipe(
...
+}
+
 const capabilities: Core.Capabilities = {
   example: Example,
   fileSystem: FileSystem,
   logger: Logger,
   ast: {
-    project: new ast.Project(),
+    project: new ast.Project({
+      compilerOptions
```
Comment (thought2) [inline src/index.ts:57]: Another way would be to read the compiler options from the user's `tsconfig.json`.
I think generally using `strict : true` is a good practice. But at the moment, I see no reason why a library shouldn't be able to make use of less strict options.

Comment (gcanti) [reply src/index.ts:57]: > Another way would be to read the compiler options from the user's tsconfig.json

Good idea (maybe in another PR), I won't export `compilerOption` for the moment (by tagging it as internal).

> I see no reason why a library shouldn't be able to make use of less strict options

Well, since this is a documentation tool for libraries in the `fp-ts` ecosystem, I'd say that `strict: true` is a basic requirement :)

**Review by gillchristian — APPROVED** [review]

**Review by IMax153 — APPROVED** [review]
Thank you @gcanti!
